export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SET_RESTAURANTS_COUNT = 'SET_RESTAURANTS_COUNT';
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SHOW_MORE_RESTAURANTS = 'SHOW_MORE_RESTAURANTS';
export const SET_PAGE = 'SET_PAGE';
